---
- name: Update packages on different operating systems
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update and upgrade packages on Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == 'Debian'

    - name: Update and upgrade packages on CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS'

    - name: Update and upgrade packages on Fedora
      dnf:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'Fedora'

    - name: Update and upgrade packages on other RedHat-based distributions
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] not in ['CentOS', 'Fedora']
